[package]
name = "xtask"
description = "Build and packaging tasks for Kestrel."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish = false

[dependencies]
anyhow.workspace = true

[lints]
workspace = true
